### ISSUE TITLE
Split into several packages

### ISSUE THREAD

**Issue by alexbiehl** [winterland1989/tcp-streams#1]
`cabal` doesn't allow passing flags to dependencies which means I can't configure `tcp-streams` to only build with `tls` library support. It will always build with `HOpenSSL` alongside which is very hard to get right on Windows. 

A solution would be to split `tcp-streams` in 3 packages: 
  - `tcp-streams` which is `tcp-streams` modulo `tls` and `HOpenSSL`
  - `tcp-streams-tls` which adds TLS support via `tls` library
  - `tcp-streams-openssl` which adds TLS support via `HOpenSSL`

**Comment by winterland1989** [comment]
There's a `cabal.project` file which you can use to assign flags, but it's only available to `new-build` system. `stack` support flag quite well i think.

But this is indeed an embarrassing problem(I'm using MacOS which always have trouble with libcrypto path). On one hand, splitting does make sense since these module is independent mostly. On the other hand this will make mantainence and the mantainence of every package depending tcp-streams(such as mysql-haskell) became quite annoying. Now they either depending on all of these packages or making a split just like what you proposed.

I have to think it over before deciding what is the best thing to do, maybe you can give more comparison on flag vs split package?

**Comment by alexbiehl** [comment]
The problem is the distribution through hackage. It doesn't use `cabal.project` or `stack.yaml` as you know that way when I want to release a new library I only have the knobs in my `cabal` file which doesn't allow passing flags to dependencies. I rather like libraries with clever defaults where I don't have to fiddle with some build-path issues and such. 

A split in `tcp-streams` would also incur a split in `mysql-haskell` which is annoying. Actually it is the package I was concerned with as I started investigating a `persistent-mysql-haskell` and I wouldn't want to include `HsOpenSSL` per default there as it imposes a burden on newcomers. 

I can't think of another way as the split. Maybe you can work out the interface in `mysql-haskell` a bit so you can plug in any TLS backend without imposing a too strong cohesion.

**Comment by winterland1989** [comment]
OK, since what we want to solve is the openssl dependency, here is my judgement:
- Split `tcp-streams` into `tcp-streams`(raw and tls) and `tcp-streams-openssl`(use HsOpenSSL).
- Split `mysql-haskell` into `mysql-haskell` and  `mysql-haskell-openssl` respectively.

You should be able to use TLS via `tcp-streams`, which use haskell `tls` package. And If you want some extra performance, `tcp-streams-openssl` is at your service as long as you can deal with the building.

Now every package depend on `tcp-streams` should follow this convention: one package with default TLS support and another one using `tcp-streams-openssl`.

As for your `persistent-mysql-haskell`, first thanks for taking time write this! is it acceptable to split a  `persistent-mysql-haskell-openssl` package? you can expose an internal module in `persistent-mysql-haskell` and use that as a basis, so `persistent-mysql-haskell-openssl`  is just a thin layer of openssl wrappers.

**Comment by alexbiehl** [comment]
@winterland1989 Yes, I think this will work. 

Ok, the plan is to create two packages:
- `persistent-mysql-haskell`
- `persistent-mysql-haskell-openssl`

This will work for me.

**Comment by winterland1989** [comment]
Done, I'll upload to hackage after some checking(cabal file ..,etc.), If you find any problem please report.
